- hosts: hostip

  vars:
   - pname: "docker"
   - nm: "docker-ce-18.09.1-3.el7.x86_64"


  tasks:

   - name: Configure Docker Repository
     yum_repository:
      name: docker
      description: docker repository
      file: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: 0


   - name: Install Docker
     package:
      name: "{{nm}}"
      state: present
     register: installation_details


   - name: Start Docker services
     service:
       name: "{{pname}}"
       state: started
       enabled: yes
     register: service_details

   - name: install python-docker module
     pip:
      name: docker-py

   - name: installation status
     debug:
       var: installation_details

   - name: service state
     debug:
       var: service_details.state

   - name: creating folder and copying local files in that folder
     file:
       path: "/task1"
       state: directory

   - name: copying local files into folder
     copy:
       src: "/task1/task1.html"
       dest: "/task1/"

   -  name: pull docker image
      docker_container:
        name: "webserver"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "2514:80"
        volumes:
        - /task1:/usr/local/apache2/htdocs/
